spring:
  application:
    name: batch-demo
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: true
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1
        jdbc:
          batch_size: 100
  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-test-query: SELECT 1 # Keep the connection alive if idle for a long time (needed in production)
      auto-commit: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  threads:
    virtual:
      enabled: true
server:
  port: 9090
